### ISSUE TITLE
How to down sample audio?

### ISSUE THREAD

**Issue by inf17101** [HEnquist/rubato#68]
Hi, I can only find examples for upsampling audio data. Currently I am trying to down sample from 48000 Hz to 16000 Hz, but I do not understand why so less values are returned.

For example I expect when passing in 48000 values that the result would be 16000 values, meaning the duration should be kept to 1 sec.
But with the following code, when passing in 4 sec recording with 48000 Hz sample rate (resulting in 192000 values), I get only a vector sized 1x639 values:

```
    use rubato::{Resampler, SincFixedIn, SincInterpolationType, SincInterpolationParameters, WindowFunction};
    let params = SincInterpolationParameters {
        sinc_len: 256,
        f_cutoff: 0.95,
        interpolation: SincInterpolationType::Linear,
        oversampling_factor: 128,
        window: WindowFunction::BlackmanHarris2,
    };
    let mut resampler = SincFixedIn::<f32>::new(
        target_sr as f64 / origin_sr as f64,
        1.0,
        params,
        2048,
        1,
    ).unwrap();

    let waves_out = resampler.process(&waves_in, None).unwrap();
    waves_out
```
I played also with the configuration parameters a bit. When increasing chunk_size from 2048 to 48000 then I get around 15000 values back. But at the end I did not get the expected output.

Could you help in this case?

Expected would be: 192000 values as input (4 sec recording) => 64000 values output (16000 Hz as 4 sec recording)

**Comment by HEnquist** [comment]
Are you doing a single call to `process()`?

Each process call does a single chunk. You create a SincFixedIn with a chunk size of 2048. That means that each process call will take 2048 frames, and produce on average 2048/3, about 683. And the first call will produce less, which is why you get ~640.

Check how it's done in the example examples/process_f64.rs. It loads a full file into ram, and then repeatedly calls process until the whole file has been processed. It can do both up- and downsampling.

**Comment by HEnquist** [comment]
I'm assuming that this was solved. Please reopen if there still are issues.
